### ISSUE TITLE
Missing dependency of "fcntl" when pip installing on windows

### ISSUE THREAD

**Issue by BenjaminDoran** [cs50/style50#23]
The library "fcntl" appears to be required for running style50, so while style50 technically installs on windows, trying to run it brings up the error of missing the "fcntl" library

fcntl appears to only be available for unix systems.

More information at this [stackoverflow post](https://stackoverflow.com/questions/1422368/fcntl-substitute-on-windows)

Possible replacement library might be [portalocker](https://pypi.python.org/pypi/portalocker) which works on cross platforms.

**Comment by cmlsharp** [comment]
Thanks for reporting this!

`style50`, and indeed most of our tools, only officially support being run on Windows via the [Linux subsystem in Windows 10](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) (though we should probably make this clearer in the `README`).

Unfortunately, the `portalocker` library does not seem to provide the subset of `fcntl`'s functionality that we are using in `style50` (the `TIOCGWINSZ` `ioctl` call for determining the size of the terminal given a file descriptor). Other cross platform options include `backports.shutil_get_terminal_size`, but unfortunately it only supports `stdout`, not arbitrary  file descriptors.  `os.get_terminal_size` does, but unfortunately it is Python 3 only and our tools need to be compatible with both Python 2 and Python 3.

I have no doubt that this functionality is possible on Windows (likely by calling the `win32api` directly) but since our other tools do not support Windows without the Linux subsystem, it does not seem particularly compelling to increase the complexity of `style50` to do so.
