### ISSUE TITLE
consolidate files?

### ISSUE THREAD

**Issue by dmalan** [cs50/style50#7]
How conventional is it to have `__main__.py`? And is `core.py` a common container for core code? Feels like it might be cleaner to have

- `__init__.py` for the package
- `checks.py` for the language-specific code, though tbh, that feels confusing vis-à-vis `check50`.  Maybe `languages.py`? Or even `lang/c.py`, `lang/js.py`, and such?
- `style50.py`, which would contain contents of `core.py` and `__main__.py`? Would be nice if running were as simple as `python style50/style50.py`, for consistent with other apps.

**Comment by cmlsharp** [comment]
`__main__.py` is very idiomatic (it's used plenty in the Python standard library).

`languages.py` seems fine, but `lang/{c, js..}.py` feels a bit excessive, especially since the checks aren't independent of one another (Java and JS inherit from C).

You'd run into some import issues with the `python style50/style50.py` approach since any relative imports inside the package (e.g. `from . import checks`) would fail since they wouldn't be in the `PYTHONPATH`. (You can see this in action now by running `python style50/__main__.py`). 

In any case, the `__main__.py` approach feels much cleaner to me since it separates "library code" from "executable code".

**Comment by dmalan** [comment]
Okay makes sense re `__main__.py`. For `core.py`, though, I was simply suggesting we consider renaming it `style50.py`, insofar as it comprises the library code. I.e., `core.py` seems somewhat arbitrary?

**Comment by cmlsharp** [comment]
Done in dcfc512b215cd46991ba13ed34b6de0007ae887a
